config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vittlify/', include('groceries.urls')),
    url(r'^$', RedirectView.as_view(url='/vittlify/')),
]

groceries/urls.py
from django.conf.urls import url
from . import (views,
               api_views,
               )

app_name = 'groceries'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^import_file/$', views.import_file, name='import_file'),
    url(r'^shopping_list_items/(?P<pk>[0-9]+)/$', api_views.ShoppingListItemsView.as_view(), name='shopping_list_items'),
    url(r'^item/(?P<pk>[0-9]+)/$', api_views.ItemView.as_view()),
    url(r'^item/$', api_views.ItemView.as_view()),
    url(r'^unsafe_item/$', api_views.UnsafeItemView.as_view()),
    url(r'^shopping_list/(?P<pk>[0-9]+)/$', api_views.ShoppingListView.as_view(), name='shopping_list-detail'),
    url(r'^shopping_list/$', api_views.ShoppingListView.as_view()),
    url(r'^shopper/(?P<pk>[0-9]+)/$', api_views.ShopperView.as_view()),
    url(r'^shopper/$', api_views.ShopperView.as_view()),
    url(r'^shared_lists/(?P<shopper_id>[0-9]+)/$', views.shared_lists),
    url(r'^shared_list_member/(?P<shopper_id>[0-9]+)/(?P<list_id>[0-9]+)/$', views.shared_list_member_json),
    url(r'^socket/(?P<pk>[0-9a-z]+)/$', api_views.WebSocketTokenView.as_view(), name='socket'),
    url(r'^category/$', api_views.ShoppingListCategoryView.as_view()),
    url(r'^sshkey/$', api_views.SshKeyView.as_view()),
    url(r'^sshkey/(?P<pk>[0-9]+)/$', api_views.SshKeyView.as_view()),
    url(r'^vt/$', api_views.CliShoppingListItemsView.as_view()),
]

groceries/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import (ShoppingList,
                     Shopper,
                     Item,
                     )

class SignInForm(forms.Form):
    username = forms.CharField(max_length=100, label='Username')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

    def clean(self):
        cleaned_data = super(SignInForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if not username or not password:
            raise forms.ValidationError('Username and password fields are required.')

        user = User.objects.filter(username__iexact=username).first()
        user = authenticate(username=user.username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError('Invalid username or password')

class ImportFileForm(forms.Form):
    import_file = forms.FileField()
    shopping_list = forms.ModelChoiceField(queryset=ShoppingList.objects.all())

    def __init__(self, *args, **kwargs):
        shopper_id = kwargs.pop('shopper_id', None)
        super(ImportFileForm, self).__init__(*args, **kwargs)
        if shopper_id:
            shopper = Shopper.objects.get(pk=shopper_id)
            self.fields['shopping_list'].queryset = ShoppingList.objects.filter(shoppinglistmember__shopper=shopper)

    def generate_items_from_file(self):
        for line in self.cleaned_data['import_file']:
            new_item = Item.new(line,
                                self.cleaned_data['shopping_list'])
            new_item.save()

groceries/views.py
from django.shortcuts import render
from django.contrib.auth import (authenticate,
                                 login,
                                 logout,
                                 )
from django.contrib.auth.models import User
from django.http import (HttpResponseRedirect,
                         JsonResponse,
                         )
from .forms import SignInForm, ImportFileForm
from .models import (Shopper,
                     RecentlyCompletedShoppingList,
                     ShoppingList,
                     ShoppingListMember,
                     WebSocketToken,
                     )
from config.settings import EXTERNAL_NODE_SERVER


def home(request):
    context = {'loggedin': False}
    user = request.user
    if user and user.is_authenticated:
        context['loggedin'] = True
        shopper = Shopper.objects.filter(user=user).first()
        shopping_lists = list(shopper.shopping_lists.all())
        context['shopping_lists'] = shopping_lists
        recently_completed_list = RecentlyCompletedShoppingList(user)
        context['shopping_lists'].append(recently_completed_list)
        context['node_server'] = EXTERNAL_NODE_SERVER

        token = WebSocketToken()
        token.active = True
        token.shopper = shopper
        token.removeOldTokens(shopper)
        token.save()

        context['socket_token'] = token.guid
        context['theme'] = shopper.theme
    return render(request, 'groceries/home.html', context)


def settings(request):
    context = {'loggedin': False}
    user = request.user

    if not user or not user.is_authenticated:
        return HttpResponseRedirect('/vittlify')

    context['node_server'] = EXTERNAL_NODE_SERVER
    context['loggedin'] = True
    owner = Shopper.objects.filter(user=user).first()
    context['owner'] = owner
    context['theme'] = owner.theme
    owned_lists = list(Shopper.objects.filter(user=user)
                                      .first()
                                      .owned_lists
                                      .all())
    context['owned_lists'] = owned_lists
    context['shoppers'] = [shopper for shopper in Shopper.objects.select_related('user').all()
                           if shopper.user != user]
    context['sshkeys'] = list(owner.sshkey_set.all())
    return render(request, 'groceries/settings.html', context)


def signin(request):
    context = {}
    context['node_server'] = EXTERNAL_NODE_SERVER
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Use a case insensitive search to find the right user
            user = User.objects.filter(username__iexact=username).first()

            if not user:
                raise Exception('Invalid User')

            # Django requires a call to authenticate
            user = authenticate(username=user.username, password=password)

            if user and user.is_active:
                login(request, user)
                context['loggedin'] = True
                context['user'] = request.user
            else:
                raise Exception('Invalid User')

            if user and 'next' in request.POST:
                return HttpResponseRedirect(request.POST['next'])
            return HttpResponseRedirect('/vittlify')
    else:
        form = SignInForm()

    context['form'] = form
    return render(request, 'groceries/signin.html', context)


def signout(request):
    logout(request)
    context = {}
    context['node_server'] = EXTERNAL_NODE_SERVER
    return render(request, 'groceries/signout.html', context)


def shared_lists(request, shopper_id):
    if request.method == 'GET':
        owner = Shopper.objects.filter(user=request.user).first()
        owned_lists = set(owner.owned_lists.all())

        shopper = Shopper.objects.get(pk=shopper_id)

        selected = set()

        for owned_list in owned_lists:
            if owned_list in shopper.shopping_lists.all():
                selected.add(owned_list)

        unselected = owned_lists.difference(selected)
        data = {'selected': [x.as_dict() for x in selected],
                'unselected': [x.as_dict() for x in unselected]}
        return JsonResponse(data)


def shared_list_member_json(request, shopper_id, list_id):
    owner = Shopper.objects.filter(user=request.user).first()
    shopping_list = ShoppingList.objects.get(pk=list_id)

    if owner != shopping_list.owner:
        raise ValueError('User is not the owner of the requested shopping list')

    shopper = Shopper.objects.get(pk=shopper_id)
    slm = (ShoppingListMember.objects
                             .filter(shopper=shopper)
                             .filter(shopping_list=shopping_list)
                             .first())

    if request.method == 'POST':
        if not slm:
            slm = ShoppingListMember.objects.create(**{'shopper': shopper,
                                                       'shopping_list': shopping_list})
            return JsonResponse(slm.as_dict(), status=201)
        else:
            return JsonResponse(slm.as_dict(), status=200)
    elif request.method == 'DELETE':
        if not slm:
            return JsonResponse({}, status=204)
        else:
            slm.delete()
            return JsonResponse({}, status=200)


def import_file(request):
    context = {'loggedin': False}
    user = request.user

    if not user or not user.is_authenticated:
        return HttpResponseRedirect('/vittlify')

    context = {'loggedin': True}
    shopper = Shopper.objects.filter(user=user).first()
    shopping_lists = list(shopper.shopping_lists.all())
    context['theme'] = shopper.theme
    context['shopping_lists'] = shopping_lists

    if request.method == 'POST':
        form = ImportFileForm(request.POST,
                              request.FILES,
                              shopper_id=shopper.id)
        if form.is_valid():
            form.generate_items_from_file()
            context['shopping_list'] = form.cleaned_data['shopping_list']
            return render(request, 'groceries/upload_success.html', context)
        else:
            context['form'] = form
            return render(request, 'groceries/upload_fail.html', context)

    return render(request, 'groceries/upload.html', context)

groceries/templates/groceries/settings.html
{% extends "groceries/home.html" %}

<!DOCTYPE html>
{% load static %}

{% include header %}

{% include title %}

{% include navbar %}


{% block main %}
<div class="page-header">
  <h1>Settings</h1>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">User info</h3>
  </div>
  <div class="panel-body">
      <div class="row">
          <div class="col-xs-5">
              <div class="form-group">
                <label for="user-email-text">Email:</label>
                <input type="text" class="form-control" id="user-email-text" value="{% if owner.email and owner.email != 'None' %}{{ owner.email }}{% endif %}" />
              </div>
              <div class="form-group">
                <label for="user-email-frequency-select">Frequency:</label>
                <select class="form-control" id="user-email-frequency-select">
                    <option value="daily" {% if owner.email_frequency == 'daily'%}selected{% endif %}>Daily</option>
                    <option value="weekly" {% if owner.email_frequency == 'weekly'%}selected{% endif %}>Weekly</option>
                    <option value="none" {% if not owner.email_frequency %}selected{% endif %}>No Emails</option>
                </select>
              </div>
              <div class="form-group">
                <button id="save-user-email-btn" class="btn btn-default" onclick="saveEmailText();">Save</button>
                <button id="clear-user-email-btn" class="btn btn-default" onclick="clearEmailText();">Clear</button>
              </div>
          </div>
          <div class="col-xs-7">
            <span id="email-saved-text"></span>
          </div>
      </div>
  </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Theme</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-1">
            </div>
            <div class="col-xs-5">
                <div class="form-group">
                    <div class="radio">
                        <label>
                            <input type="radio" checked name="theme_radio" value="default" id="theme_radio_default"/>
                            <span>Default</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="theme_radio" value="darkly" id="theme_radio_darkly"/>
                            <span>Darkly</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="theme_radio" value="journal" id="theme_radio_journal"/>
                            <span>Journal</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="theme_radio" value="readable" id="theme_radio_readable"/>
                            <span>Readable</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="theme_radio" value="united" id="theme_radio_united"/>
                            <span>United</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <span id="theme-saved-text"></span>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Your lists</h3>
  </div>
  <div class="panel-body">
      <div class="row">
          <div class="col-xs-12 col-md-7">
              <div class="form-group">
                <label for="owned-lists-select">Active lists:</label>
                <select id="owned-lists-select" name="owned-lists" size="5" class="form-control" onchange="loadCategories();">
                    {% for owned_list in owned_lists %}
                        <option value="owned_list_opt-{{ owned_list.id }}">{{ owned_list.name }}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="form-group">
                <button id="delete-list-btn" class="btn btn-default" onclick="deleteShoppingList();">Delete List</button>
              </div>
          </div>
          <div class="col-xs-12 col-md-5">
              <div class="form-group">
                    <label for="new-list-name">Add new list:</label>
                    <input type="text" class="form-control" id="new-list-name">
              </div>
              <div class="form-group">
                  <button id="add-list-btn" class="btn btn-default" onclick="addShoppingList({{owner.id}});">Add List</button>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-md-7">
              <div class="form-group">
                <label for="list-categories-select">List Categories:</label>
                <select id="list-categories-select" size="5" class="form-control">
                </select>
              </div>
          </div>
          <div class="col-xs-12 col-md-5">
              <div class="form-group">
                  <label for="new-category-name">New Category:</label>
                  <input type="text" class="form-control" id="new-category-name"/>
              </div>
              <div class="form-group">
                  <button id="add-category-btn" class="btn btn-default" onclick="addCategory();">Add Category</button>
              </div>
          </div>
      </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Sharing</h3>
  </div>
  <div class="panel-body">
      <div class="form-group">
        <label for="shopper-select">Other User:</label>
        <select id="shopper-select" class="form-control" onchange="refreshSharedLists();">
            {% for shopper in shoppers %}
                <option value="user-select-{{ shopper.id }}">{{ shopper.user.username }}</option>
            {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <select multiple id="sharing-select" size="5" class="form-control" onchange="updateSharedList();">
        </select>
      </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">SSH Keys</h3>
  </div>
  <div class="panel-body">
      {% for sshkey in sshkeys %}
          <div class="row ssh-row">
              <div class="col-xs-2">
                  <button id='delete-ssh-{{sshkey.id}}' class='btn btn-danger' onclick="deleteSSH({{sshkey.id}});">Delete</button>
              </div>
              <div class="col-xs-2">
                  <b>{{sshkey.title}}</b>
              </div>
              <div class="col-xs-4">
                  {{sshkey.fingerprint | safe}}
              </div>
              <div class="col-xs-4">
              </div>
          </div>
      {% endfor %}
      <div class="form-group">
          <label for="new-ssh-title">Title</label>
          <input type="text" class="form-control" id="new-ssh-title"/>
      </div>
      <div class="form-group">
          <label for="new-ssh-key">Key</label>
          <textarea class="form-control" id="new-ssh-key" rows="5"></textarea>
      </div>
      <div class="form-group">
          <button id="add-ssh-btn" class="btn btn-default" onclick="addSSH();">Add SSH Key</button>
            <span id="ssh-status-text"></span>
      </div>
  </div>
</div>
{% endblock %}

{% block javascript_imports %}
    <script src="{% static "jquery/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "bootstrap-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "datatables/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/ajaxSetup.js" %}"></script>
    <script src="{% static "assets/settings.js" %}"></script>
    <script src="{% static "bootstrap-duallistbox-master/jquery.bootstrap-duallistbox.min.js" %}"></script>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            token = '{{ csrf_token }}';
            owner_id = '{{ owner.id }}';

            sharing_select = $('#sharing-select').bootstrapDualListbox({
              nonSelectedListLabel: 'Available Lists',
              selectedListLabel: 'Shared',
              preserveSelectionOnMove: false,
              moveOnSelect: true,
              showFilterInputs: false
            });

            $("input[type=radio][name='theme_radio']").change(function(){
                saveThemeRadio();
            });

            refreshSharedLists();
            setThemeRadios('{{ theme }}');
        });
    </script>
{% endblock %}

groceries/templates/groceries/signin.html
{% extends "groceries/home.html" %}
<!DOCTYPE html>
{% load static %}
{% include header %}

{% include title %}

{% include navbar %}

    <div class="jumbotron">
        {% block jumbotron %}
            {% if not loggedin %}
                <h1>Grocery lists in the cloud!</h1>
                <p></p>
            {% else %}
                <h1>Logged In!</h1>
                <h3>You have logged in successfully</h3>
                <a href="/vittlify/">Go Home</a>
            {% endif %}
        {% endblock %}
    </div>

    <div class="container">
        {% block main %}
            {% if not loggedin %}
            <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-8">
                  <form action="{% url 'groceries:signin' %}" class="form-signin" role="form" method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Sign In" />
                  </form>
                </div>
                <div class="col-xs-2"></div>
            </div>
            {% endif %}
        {% endblock %}
    </div>

{% include javascript_imports %}
{% include javascript %}

groceries/templates/groceries/signout.html
{% extends "groceries/home.html" %}
<!DOCTYPE html>
{% load static %}
{% include header %}

{% include title %}

{% include navbar %}

    <div class="jumbotron">
        {% block jumbotron %}
            <h1>Logged out!</h1>
            <h3>You have logged out successfully</h3>
            <a href="/vittlify/">Go Home</a>
        {% endblock %}
    </div>

{% include main %}

{% include javascript_imports %}
{% include javascript %}

groceries/templates/groceries/upload.html
{% extends "groceries/home.html" %}

<!DOCTYPE html>
{% load static %}

{% include header %}

{% include title %}

{% include navbar %}

{% block main %}
<div class="page-header">
  <h1>Import Items from File</h1>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Upload File</h3>
  </div>
  <div class="panel-body">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="shopping-list-select">Select Shopping List</label>
            <select id="shopping-list-select" name="shopping_list" class="form-control">
                {% for shopping_list in shopping_lists %}
                    <option value="{{ shopping_list.id }}">{{ shopping_list.name }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <input name="import_file" type="file">
              {{ form.import_file.errors }}
          </div>
          <button class="btn btn-lg btn-primary" type="submit">Submit</button>
      </form>
  </div>
</div>
{% endblock %}

{% block javascript_imports %}
    <script src="{% static "jquery/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "bootstrap-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "datatables/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/ajaxSetup.js" %}"></script>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            token = '{{ csrf_token }}';
        });
    </script>
{% endblock %}

groceries/templates/groceries/upload_fail.html
{% extends "groceries/home.html" %}

<!DOCTYPE html>
{% load static %}

{% include header %}

{% include title %}

{% include navbar %}

{% block main %}
<div class="page-header">
  <h1>Error</h1>
</div>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Upload Failed!</h3>
  </div>
  <div class="panel-body">
      There was an error attempting to import the selected file. Check that the file is valid and try again.
  </div>
</div>
{% endblock %}

{% block javascript_imports %}
    <script src="{% static "jquery/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "bootstrap-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "datatables/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/ajaxSetup.js" %}"></script>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            token = '{{ csrf_token }}';
        });
    </script>
{% endblock %}

groceries/templates/groceries/upload_success.html
{% extends "groceries/home.html" %}

<!DOCTYPE html>
{% load static %}

{% include header %}

{% include title %}

{% include navbar %}

{% block main %}
<div class="page-header">
  <h1>Success</h1>
</div>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Upload Successful!</h3>
  </div>
  <div class="panel-body">
      File was successfully imported into the {{ shopping_list.name }} list. You will be redirected back to the home screen shortly.
  </div>
</div>
{% endblock %}

{% block javascript_imports %}
    <script src="{% static "jquery/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "bootstrap-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "datatables/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/ajaxSetup.js" %}"></script>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            setTimeout("location.href = '/';",5000);
        });
    </script>
{% endblock %}